language: rust
notifications:
    irc: "irc.mozilla.org#piston-internals"
os:
    - linux
    - osx
env:
    global:
        - secure: BjBU6fxOowldOZ30FDcB13/al7nEFnvrOPwumhHRlApAP7favgTzKXfuIOL3r4ZiLsr8Hw4OK038bS+Mv941KVAp0AMYgOqyWzdBbFTHzs4hGVnC6OlqrtVmPzBEmyjbJwUjTsXnVfufQBKKSJhDDcuj83Hkr3L+5LGESnTewAE=
        - LD_LIBRARY_PATH: /usr/local/lib
before_install:
    - curl -O http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
    - tar -xzvf SDL2-2.0.0.tar.gz
install:
    - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
before_script:
    - rustc -v
    - cargo -V
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
